# Generated by Django 2.2.14 on 2022-02-28 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newBillAmount', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('uniqueId', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hosteler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosteler', models.CharField(max_length=100)),
                ('fee', models.BooleanField(blank=True, null=True)),
                ('room_number', models.CharField(max_length=5)),
                ('uniqueId', models.TextField()),
                ('messBillPaid', models.BooleanField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mess_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MessBill')),
            ],
        ),
    ]
