# Generated by Django 2.2.14 on 2022-02-28 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spaceFor', models.IntegerField(blank=True, null=True)),
                ('occupiedBy', models.IntegerField(blank=True, null=True)),
                ('rentCost', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hosteler',
            options={'ordering': ['-uniqueId']},
        ),
        migrations.AddField(
            model_name='hosteler',
            name='roomType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.RoomType'),
        ),
    ]
