# Generated by Django 2.2.14 on 2022-05-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220301_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
