# Generated by Django 2.2.14 on 2022-05-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_roomtype_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='room_number',
        ),
    ]
